### PR TITLE
HexGrid now can create Dregions for Subbarrel pattern code

### PR DESCRIPTION
**Pull request by jmartinbrooke**

### CODE REVIEW

**Comment by jmartinbrooke** [comment]
I have no intention of merging with master at present.

**Comment by jmartinbrooke** [comment]
I do not understand the difference between what I see locally and what Seb's comments refer to. So I will wait and just work locally at present.

**Comment by sebjameswml** [comment]
It seems like you haven't added your local version of the files to the feature/dregions branch. What does git status tell you?

**Comment by jmartinbrooke** [comment]
On branch feature/dregions
Your branch is up-to-date with 'origin/feature/dregions'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

modified:   tests/testVisual.cpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)

.CMakeLists.txt.swp
boundaries/barrelAE.svg
boundaries/barrelBoundary.svg
boundaries/trial1.svg
diff.txt
err
src/

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by sebjameswml** [comment]
Given that git status output, I would be very surprised if the files in your local version of the code were different from the files on the morphologica branch feature/dregions

You could clone a fresh copy of morphologica, change it to feature/dregions and try to verify:

diff -Naur path/to/original/morphologica/morph/HexGrid.h path/to/newlycloned/morphologica/morph/HexGrid.h

**Comment by jmartinbrooke** [comment]
Hi Seb, I am trying to do as you suggest, i.e. I created a clean directory, downloaded morphologica, switched to feature/dregions and sent a pull request. I get the message that "John Brooke wants to merge commits with master..." I left it there because until this is sorted I dont want to cause hassle by merging with the master on origin. I think that the message means that my local version of master will be merged and that this will not affect the origin version. Is this correct, I really dont want to cause you extra work by undoing my mistakes,

**Comment by sebjameswml** [comment]
Hi John, I've changed the code a bit to remove your last wrapper function. I committed ddc0823 which is uncontroversial. Then, take a look at f1bd937 - you'll see I employed the same idea with a second argument with a default value. You'll need to change your code to call setBoundary(bezcurvepath, false) instead of setBoundaryDRegion(bezcurvepath). If you're happy with this change, I will merge this pull request into master.

**Comment by sebjameswml** [comment]
John has tested and so we're ready to merge this in.

**Comment by sebjameswml** [comment]
Whoops, need to merge before closing

**Comment by sebjameswml** [comment]
Sorted

**Pull request merged**
